version: '3.8'

services:
  ion-api:
    image: ion-organizer-api
    networks:
      - ion
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080

  ion-ui:
    image: ion-organizer-ui
    networks:
      - ion
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - 80:80

networks:
  ion:
